/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import calendariotorneo.CalendarioTorneo1;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author dell
 */
public class jFCalendario extends javax.swing.JFrame {

    CalendarioTorneo1 calendarioTorneo;
    DefaultTableModel dtmTablaPosiciones;
    public jFCalendario() {
        initComponents();
        calendarioTorneo = new CalendarioTorneo1();
        dtmTablaPosiciones = new DefaultTableModel();
        crearColumnas();
        for (int i = 0; i < calendarioTorneo.tablaPosiciones.length; i++) {
            dtmTablaPosiciones.addRow(new Object[]{calendarioTorneo.tablaPosiciones[i][0],
            calendarioTorneo.tablaPosiciones[i][1],calendarioTorneo.tablaPosiciones[i][2],
            calendarioTorneo.tablaPosiciones[i][3],calendarioTorneo.tablaPosiciones[i][4],
            calendarioTorneo.tablaPosiciones[i][5],calendarioTorneo.tablaPosiciones[i][6],
            calendarioTorneo.tablaPosiciones[i][7],calendarioTorneo.tablaPosiciones[i][8],});        
        }
        this.jTable1.setModel(dtmTablaPosiciones);

    }

    public void crearColumnas(){
        dtmTablaPosiciones.addColumn("Club");
        dtmTablaPosiciones.addColumn("PJ");
        dtmTablaPosiciones.addColumn("PG");
        dtmTablaPosiciones.addColumn("PE");
        dtmTablaPosiciones.addColumn("PP");
        dtmTablaPosiciones.addColumn("GF");
        dtmTablaPosiciones.addColumn("GC");
        dtmTablaPosiciones.addColumn("DG");
        dtmTablaPosiciones.addColumn("PTS");      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTAMostrarJornada = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBJugar1Partido = new javax.swing.JButton();
        jBJugarTodosPartidos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTAMostrarJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 520, 270));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 740, 380));

        jBJugar1Partido.setText("JUGAR UNA FECHA");
        jBJugar1Partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJugar1PartidoActionPerformed(evt);
            }
        });
        getContentPane().add(jBJugar1Partido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jBJugarTodosPartidos.setText("JUGAR TODOS PARTIDOS");
        getContentPane().add(jBJugarTodosPartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/FondoFutbol.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 650));

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBJugar1PartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJugar1PartidoActionPerformed
        
    }//GEN-LAST:event_jBJugar1PartidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFCalendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBJugar1Partido;
    private javax.swing.JButton jBJugarTodosPartidos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jTAMostrarJornada;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
